#!/bin/bash

# latexit v3.1
# created ks feb 24 2022
# last updated ks feb 26 2022

START=$(date +%s)

name='latexit'
here=$(pwd)
base=${here}/${name}

color='black'
saveas=${base}.png
verbose='false'
quality=10
height=72
expression=""

print_usage(){
  echo 'usage: latexit [-c <color>] [-s <save as...>] [-v] [-q <quality>] [-H <height>] -e "<expression>"'
  echo 'hints:'
  echo '  color names are provided by xcolor package'
  echo "  color shading is possible but should be entered with a single quotation: 'green!50!black'"
  echo '  verbose flag has no effect at the moment'
  echo 'default settings:'
  echo "  font color is ${color}"
  echo "  save location is ${saveas}"
  echo "  verbose is ${verbose}"
  echo "  quality is ${quality}"
  echo "  height is ${height}"
}

print_settings(){
  echo 'current settings:'
  echo "  font color is ${color}"
  echo "  save as... path is ${saveas}"
  echo "  verbose is ${verbose}"
  echo "  quality is ${quality}"
  echo "  height is ${height}"
  echo "  expression is ${expression}"
}

while getopts 'c:s:vq:H:e:' flag
do
  case "${flag}" in
    c) color="${OPTARG}" ;;
    s) saveas="${OPTARG}" ;;
    v) verbose='true' ;;
    q) quality="${OPTARG}" ;;
    H) height="${OPTARG}" ;;
    e) expression="${OPTARG}" ;;
    *) echo 'hint: run `latexit`'
       exit 1 ;;
  esac
done

# check if not a flag is given
if [[ ! $@ =~ ^\-.+ ]]
then
  print_usage

# check if the expression flag is missing
elif [[ "$@" != *"-e"* ]]
then
  echo 'error: missing flag -- e'
else
  # prepare the tex file
  cat > ${saveas%.*}.tex <<EOL
    \documentclass{standalone}
    \usepackage{amsmath,amssymb,mathrsfs,slashed,bm,xcolor}
    \def\pp#1{\left( #1 \right)}
    \def\bb#1{\left[ #1 \right]}
    \def\cc#1{\left\{ #1 \right\}}
    \def\vv#1{\left\vert #1 \right\vert}
    \def\bra#1{\langle #1 \vert}
    \def\ket#1{\vert #1 \rangle}
    \def\pmat#1{\begin{pmatrix}#1\end{pmatrix}}
    \def\bmat#1{\begin{bmatrix}#1\end{bmatrix}}
    \def\vmat#1{\begin{vmatrix}#1\end{vmatrix}}
    \def\del{\partial}
    \def\Lag{\mathscr L}
    \def\Mt{\mathscr M}
    \def\nn{\nonumber \\\\ &}
    \DeclareMathOperator{\sech}{sech}
    \def\vec#1{\bm{\mathrm{#1}}}
    \def\hvec#1{\hat{\bm{\mathrm{#1}}}}
    \def\vvec#1{\vv{\bm{\mathrm{#1}}}}
    \DeclareMathOperator{\re}{\mathrm{Re}}
    \DeclareMathOperator{\im}{\mathrm{Im}}
    \DeclareMathOperator{\tr}{\mathrm{tr}}
    \DeclareMathOperator{\diag}{\mathrm{diag}}
    \DeclareMathOperator{\var}{\mathrm{var}}
    \def\doublevec#1{\stackrel{\leftrightarrow}{#1}}
    \def\d{\mathop{}\!\mathrm{d}}
    \def\D#1{\mathop{}\!\mathrm{d^#1}}
    \def\e{\mathop{}\!\mathrm{e}}
    \def\I{\mathop{}\!\mathrm{i}}
    \begin{document}
EOL

  echo "\color{${color}}" >> ${saveas%.*}.tex
  echo '$\displaystyle' >> ${saveas%.*}.tex
  echo '\begin{aligned}' >> ${saveas%.*}.tex
  echo "${expression}" >> ${saveas%.*}.tex
  echo '\end{aligned}' >> ${saveas%.*}.tex
  echo '$' >> ${saveas%.*}.tex
  echo '\end{document}' >> ${saveas%.*}.tex
  
  # print current settings
  print_settings
  
  # compile the tex file to dvi
  latex -halt-on-error -shell-escape ${saveas%.*}.tex 1> ${saveas%.*}.stdout 2> ${saveas%.*}.stderr

  if grep -q 'No pages of output.' ${saveas%.*}.stdout
  then
    # finalize
    echo 'error: check syntax'
    echo 'error: possible sources of error in'
    echo "  expression: ${expression}"
    echo "  color: ${color}"
    echo 'exit: no output produced'
   
    # get duration
    END=$(date +%s)
    DUR=$((END - START))
    echo "exit: ${DUR} second(s)"
 
    # remove leftovers
    rm ${saveas%.*}.aux ${saveas%.*}.dvi ${saveas%.*}.log ${saveas%.*}.tex ${saveas%.*}.stdout ${saveas%.*}.stderr ${saveas%.*}.eps &> /dev/null
  else
    # convert dvi to eps
    dvips -E -o ${saveas%.*}.eps ${saveas%.*}.dvi 1>> ${saveas%.*}.stdout 2>> ${saveas%.*}.stderr

    # convert eps to png
    convert -density $(echo "${quality} * 100" | bc -l) ${saveas%.*}.eps ${saveas%.*}.png &> /dev/null
    
    # trim white spaces
    convert ${saveas%.*}.png -trim ${saveas%.*}.png &> /dev/null
    
    # resize to height
    convert -resize x${height} ${saveas%.*}.png -density $(echo "${quality} * 100" | bc -l) ${saveas%.*}.png &> /dev/null
 
    # remove leftovers
    rm ${saveas%.*}.aux ${saveas%.*}.dvi ${saveas%.*}.log ${saveas%.*}.tex ${saveas%.*}.stdout ${saveas%.*}.stderr ${saveas%.*}.eps &> /dev/null
  
    # copy png to clipboard
    xclip -selection clipboard -t image/png -i ${saveas}

    # finalize
    echo "image saved as ${saveas} and copied to clipboard"
    echo 'exit: success'
    
    # get duration
    END=$(date +%s)
    DUR=$((END - START))
    
    if [ ${DUR} -gt 1 ]
    then
      echo "exit: ${DUR} seconds"
    else
      echo "exit: ${DUR} second"
    fi

    if [ ${DUR} -gt 2 ]
    then
      echo 'hint: took longer than expected'
      echo 'hint: try reducing quality'
    fi
  fi
fi
